from src.InputSystem import InputAction

class Manager:
    def __init__(self): ...
    def handle_event(self, event: InputAction): ...
    def update(self): ...
    def render(self): ...
    def enter(self): ...
    def exit(self): ...