from src.InputSystem import InputAction

class Manager:
    def __init__(self) -> None: ...
    def handle_event(self, event: InputAction) -> None: ...
    def update(self) -> None: ...
    def render(self) -> None: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...