from src.InputSystem import InputAction


class BaseSurface:
    def enter(self) -> None: ...
    def update(self) -> None: ...
    def handle_event(self, event: InputAction) -> None: ...
    def afterRender(self) -> None: ...
    def render(self) -> None: ...
    def beforeRender(self) -> None: ...
    def exit(self) -> None: ...