import pygame

from src.InputSystem import InputAction


class BaseSurface:
    def __init__(self) -> None:
        self.surface_display = pygame.display.get_surface()

    def update_surface(self) -> None:
        self.surface_display = pygame.display.get_surface()

    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def update(self) -> None: ...
    def handle_event(self, event: InputAction) -> None: ...
    def beforeRender(self) -> None: ...
    def render(self) -> None: ...
    def afterRender(self) -> None: ...