from src.InputSystem import InputAction


class Manager:
    def enter(self): ...
    def exit(self): ...
    def update(self): ...
    def handle_event(self, event: InputAction): ...
    def render(self): ...