from src.InputSystem import InputAction


class Manager:
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def update(self) -> None: ...
    def handle_event(self, event: InputAction) -> None: ...
    def render(self) -> None: ...